AWSTemplateFormatVersion: '2010-09-09'
Description: Move Files Dropbox

Parameters:
  Environment:
    Type: String
    AllowedValues:
    - production
  Version:
    Type: String
  ClusterName:
    Type: String
    Default: move-files-dropbox

Resources:
  MoveFilesS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: marino-dropbox-move-files
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  MoveFilesLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: GetCredentials
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource:
                  - !Sub '${MoveFilesS3Bucket.Arn}/credentials.json'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  MoveFilesLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub 'move-files-dropbox-releases-${AWS::Region}'
        S3Key: !Sub "${Version}/move-files-dropbox.zip"
      Description: Transform files between directories
      Handler: move_files.index.handler
      Environment:
        Variables:
          CREDENTIALS_LOCATION: !Sub 's3://${MoveFilesS3Bucket}/credentials.json'
      MemorySize: 256
      Role: !GetAtt MoveFilesLambdaRole.Arn
      Runtime: python3.11
      Timeout: 300
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName
      - Key: Environment
        Value: !Ref Environment

  DailyProcessTrigger:
    Type: AWS::Events::Rule
    Properties:
      Description: 'Process daily files from dropbox'
      ScheduleExpression: rate(30 minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt MoveFilesLambda.Arn
          Id: !Sub 'DailyTriggerMoveFiles-${Environment}'

  DailyProcessTriggerPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MoveFilesLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyProcessTrigger.Arn



